apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}
  minReplicas: {{ .Values.scaller.minReplicas }}
  maxReplicas: {{ .Values.scaller.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: {{ .Values.scaller.type }}
          averageUtilization: {{ .Values.scaller.averageUtilization }} 